var srcIndex = new Map(JSON.parse('[\
["mistralrs",["",[],["lib.rs"]]],\
["mistralrs_bench",["",[],["main.rs"]]],\
["mistralrs_core",["",[["aici",[],["bintokens.rs","bytes.rs","cfg.rs","lex.rs","mod.rs","recognizer.rs","rx.rs","svob.rs","toktree.rs"]],["amoe",[],["inputs.rs","macros.rs","mod.rs"]],["cublaslt",[],["mod.rs"]],["cuda",[],["ffi.rs","mod.rs"]],["dummy_paged_attention",[["layers",[],["mod.rs","paged_attention.rs"]]],["block_engine.rs","block_engine_sequence.rs","cache_engine.rs","config.rs","mod.rs","scheduler.rs"]],["engine",[],["mod.rs"]],["gguf",[],["chat_template.rs","content.rs","gguf_tokenizer.rs","mod.rs"]],["lora",[],["loralinear.rs","mod.rs","qloralinear.rs"]],["models",[],["gemma.rs","gemma2.rs","llama.rs","mistral.rs","mixtral.rs","mod.rs","phi2.rs","phi3.rs","phi3_5_moe.rs","quantized_llama.rs","quantized_phi2.rs","quantized_phi3.rs","quantized_starcoder2.rs","qwen2.rs","starcoder2.rs"]],["pipeline",[["loaders",[],["mod.rs","normal_loaders.rs","vision_loaders.rs"]]],["amoe.rs","cache_manager.rs","chat_template.rs","ggml.rs","gguf.rs","inputs_processor.rs","isq.rs","macros.rs","mod.rs","normal.rs","paths.rs","processing.rs","sampling.rs","speculative.rs","vision.rs"]],["scheduler",[],["default_scheduler.rs","mod.rs"]],["tools",[],["mod.rs","request.rs","response.rs"]],["topology",[],["mod.rs"]],["utils",[],["debug.rs","gguf_metadata.rs","memory_usage.rs","mod.rs","model_config.rs","normal.rs","progress.rs","tokenizer.rs","tokens.rs","varbuilder_utils.rs"]],["vision_models",[["llava",[["llava_llm",[],["llama.rs","mistral.rs","mod.rs"]]],["config.rs","llava15.rs","llava_inputs_processor.rs","llava_next.rs","llava_next_inputs_processor.rs","mod.rs","utils.rs"]]],["clip.rs","idefics2.rs","idefics2_input_processor.rs","image_processor.rs","mod.rs","phi3.rs","phi3_inputs_processor.rs","preprocessor_config.rs","processor_config.rs"]],["xlora_models",[],["classifier.rs","config.rs","gemma.rs","gemma2.rs","llama.rs","mistral.rs","mixtral.rs","mod.rs","phi2.rs","phi3.rs","quantized_llama.rs","quantized_phi3.rs","starcoder2.rs"]]],["attention.rs","device_map.rs","layers.rs","layers_masker.rs","layers_utils.rs","lib.rs","model_loader.rs","model_selected.rs","ops.rs","prefix_cacher.rs","request.rs","response.rs","sampler.rs","sequence.rs","toml_selector.rs"]]],\
["mistralrs_paged_attn",["",[],["lib.rs"]]],\
["mistralrs_quant",["",[["gguf",[],["mod.rs"]],["gptq",[],["gptq_cpu.rs","mod.rs"]],["hqq",[],["hqq_cpu.rs","mod.rs","optimize.rs","quantize.rs"]],["unquantized",[],["mod.rs"]],["utils",[],["isq.rs","mod.rs","ops.rs"]]],["lib.rs"]]],\
["mistralrs_server",["",[],["chat_completion.rs","completions.rs","interactive_mode.rs","main.rs","openai.rs"]]],\
["mistralrs_vision",["",[],["lib.rs","ops.rs","transforms.rs","utils.rs"]]]\
]'));
createSrcSidebar();
