mistralrs_metal_compile::metal_source_set! {
    pub const QUANT_METAL_SOURCE_SET;
    library_name: "mistralrs_quant",
    source_dir: "src/metal_kernels",
    metal_sources: [
        "bitwise",
        "blockwise_fp8",
        "bnb_dequantize",
        "f8q8",
        "flash_attn",
        "fused_glu",
        "hqq_dequantize",
        "hqq_bitpack",
        "moe",
        "mxfp4",
        "quantized",
        "rotary",
        "rmsnorm_residual",
        "scalar_fp8",
        "scan",
        "sdpa_with_sinks",
        "softcap",
        "softmax_with_sinks",
        "sort",
        "copy",
        "topk_logits",
    ],
    header_sources: ["utils", "bf16", "scan_impl", "sort_impl", "copy_impl"],
    include_only_sources: ["float8", "float4"],
}
