#!/usr/bin/env bash
# kbd-generate-commands.sh
#
# Reads .agent/skills/kbd-process-orchestrator/workflows/workflows.yaml
# and fans out slash command .md files to all supported AI tool directories.
#
# Supported tools:
#   - Antigravity / Gemini AI   → .agent/workflows/
#   - Claude Code               → .claude/commands/
#   - Cursor Agent              → .cursor/commands/
#   - Cline                     → .clinerules/workflows/
#   - OpenCode                  → .opencode/commands/
#   - Windsurf Cascade          → .windsurf/workflows/
#
# Usage:
#   bash .agent/skills/kbd-process-orchestrator/scripts/kbd-generate-commands.sh
#   bash .agent/skills/kbd-process-orchestrator/scripts/kbd-generate-commands.sh --dry-run
#   bash .agent/skills/kbd-process-orchestrator/scripts/kbd-generate-commands.sh --tool claude
#
# Idempotent: safe to re-run. Existing files are overwritten.

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "${SKILL_DIR}/../../../" && pwd)"
WORKFLOWS_YAML="${SKILL_DIR}/workflows/workflows.yaml"
TEMPLATES_DIR="${SKILL_DIR}/workflows/templates"
DRY_RUN=false
TARGET_TOOL=""

# Parse args
for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
    --tool=*) TARGET_TOOL="${arg#*=}" ;;
  esac
done

# Tool output directories (relative to project root)
declare -A TOOL_DIRS=(
  [antigravity]=".agent/workflows"
  [claude]=".claude/commands"
  [cursor]=".cursor/commands"
  [cline]=".clinerules/workflows"
  [opencode]=".opencode/commands"
  [windsurf]=".windsurf/workflows"
)

# Tool-specific header comment (written at top of each generated file)
declare -A TOOL_HEADERS=(
  [antigravity]="<!-- Generated by kbd-generate-commands.sh — Antigravity workflow -->"
  [claude]="<!-- Generated by kbd-generate-commands.sh — Claude Code custom command -->"
  [cursor]="<!-- Generated by kbd-generate-commands.sh — Cursor Agent custom command -->"
  [cline]="<!-- Generated by kbd-generate-commands.sh — Cline workflow -->"
  [opencode]="<!-- Generated by kbd-generate-commands.sh — OpenCode custom command -->"
  [windsurf]="<!-- Generated by kbd-generate-commands.sh — Windsurf Cascade workflow -->"
)

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " KBD Command Generator"
echo " Source: ${WORKFLOWS_YAML}"
echo " Target: ${PROJECT_ROOT}"
if [[ "$DRY_RUN" == "true" ]]; then
  echo " Mode: DRY RUN (no files written)"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check for yq (YAML parser)
if ! command -v yq &>/dev/null; then
  echo "⚠ yq not found. Install with: brew install yq"
  echo "  Falling back to python3 yaml parsing..."
  USE_PYTHON=true
else
  USE_PYTHON=false
fi

# Parse workflows.yaml and generate per command
generate_commands() {
  local tool="$1"
  local out_dir="${PROJECT_ROOT}/${TOOL_DIRS[$tool]}"
  local header="${TOOL_HEADERS[$tool]}"

  echo "→ Tool: $tool  →  ${TOOL_DIRS[$tool]}"

  # Read workflow names from YAML
  if [[ "$USE_PYTHON" == "true" ]]; then
    NAMES=$(python3 -c "
import yaml, sys
with open('${WORKFLOWS_YAML}') as f:
    data = yaml.safe_load(f)
for w in data.get('workflows', []):
    print(w['name'])
")
  else
    NAMES=$(yq '.workflows[].name' "${WORKFLOWS_YAML}")
  fi

  while IFS= read -r name; do
    [[ -z "$name" ]] && continue

    # Read description and args from YAML
    if [[ "$USE_PYTHON" == "true" ]]; then
      DESC=$(python3 -c "
import yaml
with open('${WORKFLOWS_YAML}') as f:
    data = yaml.safe_load(f)
for w in data.get('workflows', []):
    if w['name'] == '${name}':
        print(w.get('description', ''))
        break
")
      SKILL=$(python3 -c "
import yaml
with open('${WORKFLOWS_YAML}') as f:
    data = yaml.safe_load(f)
for w in data.get('workflows', []):
    if w['name'] == '${name}':
        print(w.get('skill', '') or '')
        break
")
    else
      DESC=$(yq ".workflows[] | select(.name == \"${name}\") | .description" "${WORKFLOWS_YAML}")
      SKILL=$(yq ".workflows[] | select(.name == \"${name}\") | .skill // \"\"" "${WORKFLOWS_YAML}")
    fi

    # Determine output file (Cline uses .md suffix in the command name)
    if [[ "$tool" == "cline" ]]; then
      OUT_FILE="${out_dir}/${name}.md"
    else
      OUT_FILE="${out_dir}/${name}.md"
    fi

    # Build the template content
    TEMPLATE="${TEMPLATES_DIR}/${name}.md"
    if [[ -f "$TEMPLATE" ]]; then
      CONTENT=$(cat "$TEMPLATE")
    else
      # Fallback: generate minimal content from SKILL.md reference
      CONTENT="Read \`${SKILL}\` and execute the /${name} workflow.

Pass any arguments provided after the command to the skill as context.

Arguments: \$ARGUMENTS"
    fi

    # Build the full file content, adapting frontmatter per tool
    case "$tool" in
      claude)
        # Claude Code uses YAML frontmatter with description and allowed-tools
        FILE_CONTENT="---
description: ${DESC}
allowed-tools: Bash, Read, Write, Edit, Glob, Grep, WebFetch, WebSearch
---

${header}

${CONTENT}"
        ;;
      cursor)
        # Cursor: simple markdown, no frontmatter required
        FILE_CONTENT="${header}

# /${name}

${DESC}

${CONTENT}"
        ;;
      cline)
        # Cline: simple markdown, invoked as /name.md
        FILE_CONTENT="${header}

# ${name}

${DESC}

${CONTENT}"
        ;;
      opencode)
        # OpenCode: supports description property in frontmatter
        FILE_CONTENT="---
description: ${DESC}
---

${header}

${CONTENT}"
        ;;
      windsurf)
        # Windsurf: workflows directory, markdown
        FILE_CONTENT="${header}

# ${name}

${DESC}

${CONTENT}"
        ;;
      antigravity)
        # Antigravity: existing workflow format with description frontmatter
        FILE_CONTENT="---
description: ${DESC}
---

${CONTENT}"
        ;;
    esac

    if [[ "$DRY_RUN" == "true" ]]; then
      echo "  [dry-run] Would write: ${OUT_FILE}"
    else
      mkdir -p "$out_dir"
      echo "$FILE_CONTENT" > "$OUT_FILE"
      echo "  ✓ ${name}.md"
    fi

  done <<< "$NAMES"
  echo ""
}

# Generate for all tools (or just the specified one)
for tool in "${!TOOL_DIRS[@]}"; do
  if [[ -n "$TARGET_TOOL" && "$TARGET_TOOL" != "$tool" ]]; then
    continue
  fi
  generate_commands "$tool"
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Done."
echo ""
echo " Commands are now registered for:"
for tool in "${!TOOL_DIRS[@]}"; do
  if [[ -z "$TARGET_TOOL" || "$TARGET_TOOL" == "$tool" ]]; then
    echo "   • $tool  →  ${TOOL_DIRS[$tool]}"
  fi
done
echo ""
echo " Run /kbd-init --update-commands to regenerate from workflows.yaml"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
