#!/usr/bin/env python3
"""
Render the runnable example trees as Starlight Markdown pages.

Walks `mistralrs/examples/**/main.rs` (Rust SDK), `examples/python/**/*.py`
(Python SDK), and `examples/server/**/*.py` (HTTP API), extracts the leading
doc header (`//!` lines for Rust, the module docstring for Python), and
writes one page per example into `docs/src/content/docs/examples/`. The
output directory layout mirrors the source trees so Starlight's sidebar
`autogenerate` rule groups pages by source directory.

Run from the repo root or the docs directory.
"""

from __future__ import annotations

import ast
import shutil
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
WEBSITE_DIR = SCRIPT_DIR.parent
REPO_DIR = WEBSITE_DIR.parent
OUT_DIR = WEBSITE_DIR / "src" / "content" / "docs" / "examples"
GITHUB_BLOB_BASE = "https://github.com/EricLBuehler/mistral.rs/blob/master/"
NEEDS_HEADER_MARKER = "<!-- needs-header -->"

# (sidebar dir, source root relative to repo, label used in stub blurbs)
TREES = [
    ("rust", "mistralrs/examples", "Rust SDK"),
    ("python", "examples/python", "Python SDK"),
    ("server", "examples/server", "HTTP server"),
]


def _rust_header(source: str) -> str:
    lines = []
    for line in source.splitlines():
        if line.startswith("//!"):
            lines.append(line[3:].removeprefix(" "))
        elif line.strip() == "" and not lines:
            continue
        else:
            break
    return "\n".join(lines).strip()


def _python_header(source: str) -> str:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return ""
    return (ast.get_docstring(tree) or "").strip()


def _slug(name: str) -> str:
    return name.replace("_", "-")


def _yaml_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _title_from_header(header: str, fallback: str) -> str:
    first = next((ln.strip() for ln in header.splitlines() if ln.strip()), "")
    if not first:
        return fallback
    return first.rstrip(".")


def _render_page(
    src: Path, header: str, lang: str, sidebar_label: str, tree_label: str
) -> str:
    rel = src.relative_to(REPO_DIR).as_posix()
    title = _title_from_header(header, sidebar_label)
    if header:
        blurb = header
    else:
        blurb = (
            f"Runnable {tree_label} example `{sidebar_label}`.\n\n{NEEDS_HEADER_MARKER}"
        )

    code = src.read_text().rstrip("\n")
    fence = "````" if "```" in code else "```"

    return "\n".join(
        [
            "---",
            f"title: {_yaml_quote(title)}",
            f"description: {_yaml_quote(title)}",
            "sidebar:",
            f"  label: {_yaml_quote(sidebar_label)}",
            "---",
            "",
            "<!-- generated by docs/scripts/render_examples.py; edit the source example instead -->",
            "",
            blurb,
            "",
            f"{fence}{lang}",
            code,
            fence,
            "",
            f"Source: [`{rel}`]({GITHUB_BLOB_BASE}{rel})",
            "",
        ]
    )


def _collect(tree_dir: str, source_root: Path) -> list[tuple[Path, Path, str]]:
    """Return [(source file, output path, language)] for one tree."""
    out: list[tuple[Path, Path, str]] = []
    if tree_dir == "rust":
        for src in sorted(source_root.rglob("main.rs")):
            rel_parts = src.parent.relative_to(source_root).parts
            dest = OUT_DIR / "rust" / Path(*[_slug(p) for p in rel_parts])
            out.append((src, dest.with_suffix(".md"), "rust"))
    else:
        for src in sorted(source_root.rglob("*.py")):
            rel = src.relative_to(source_root).with_suffix("")
            dest = OUT_DIR / tree_dir / Path(*[_slug(p) for p in rel.parts])
            out.append((src, dest.with_suffix(".md"), "python"))
    return out


def _render_index(counts: dict[str, int]) -> str:
    lines = [
        "---",
        "title: Examples",
        'description: "Runnable examples for the Rust SDK, Python SDK, and HTTP server."',
        "sidebar:",
        "  order: 1",
        "---",
        "",
        "Every page in this section is generated from a runnable example in the repository.",
        "",
        "| Tree | Source | Pages |",
        "| --- | --- | --- |",
    ]
    for tree_dir, source_rel, label in TREES:
        lines.append(
            f"| {label} | [`{source_rel}`]({GITHUB_BLOB_BASE}{source_rel}) | {counts[tree_dir]} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    counts: dict[str, int] = {}
    missing_headers = 0
    total = 0
    for tree_dir, source_rel, label in TREES:
        source_root = REPO_DIR / source_rel
        if not source_root.is_dir():
            print(f"error: {source_root} does not exist", file=sys.stderr)
            return 1
        entries = _collect(tree_dir, source_root)
        counts[tree_dir] = len(entries)
        for src, dest, lang in entries:
            source = src.read_text()
            header = _rust_header(source) if lang == "rust" else _python_header(source)
            if not header:
                missing_headers += 1
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(
                _render_page(
                    src,
                    header,
                    lang,
                    src.parent.name if lang == "rust" else src.stem,
                    label,
                )
            )
            total += 1

    (OUT_DIR / "index.md").write_text(_render_index(counts))
    print(f"wrote {total} example pages + index to {OUT_DIR}")
    if missing_headers:
        print(
            f"note: {missing_headers} examples have no doc header (marked {NEEDS_HEADER_MARKER})"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
