use candle_core::cuda::cudarc::driver::sys::CUstream;
use half::{bf16, f16};

use super::moe_cuda::RoutedLoraAdapterWeight;

extern "C" {
    pub fn routed_lora_metadata_workspace_size(num_experts: i32, num_adapter_slots: i32) -> usize;

    pub fn launch_routed_lora_build_metadata(
        token_adapter_slots: *const u32,
        topk_expert_ids: *const u32,
        route_pair_ids: *mut u32,
        pair_counts: *mut u32,
        pair_offsets: *mut u32,
        pair_cursors: *mut u32,
        sorted_route_ids: *mut u32,
        block_pair_ids: *mut u32,
        num_active_routes: *mut u32,
        num_padded_routes: *mut u32,
        num_tokens: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        block_size: i32,
        max_padded_routes: i32,
        max_blocks: i32,
        scan_workspace: *mut core::ffi::c_void,
        scan_workspace_bytes: usize,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_direct_f32(
        input: *const f32,
        output: *mut f32,
        weights: *const RoutedLoraAdapterWeight,
        token_adapter_slots: *const u32,
        topk_expert_ids: *const u32,
        route_input_rows: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_tokens: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        max_rank: i32,
        input_mode: i32,
        output_splits: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_direct_f16(
        input: *const f16,
        output: *mut f16,
        weights: *const RoutedLoraAdapterWeight,
        token_adapter_slots: *const u32,
        topk_expert_ids: *const u32,
        route_input_rows: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_tokens: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        max_rank: i32,
        input_mode: i32,
        output_splits: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_direct_bf16(
        input: *const bf16,
        output: *mut bf16,
        weights: *const RoutedLoraAdapterWeight,
        token_adapter_slots: *const u32,
        topk_expert_ids: *const u32,
        route_input_rows: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_tokens: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        max_rank: i32,
        input_mode: i32,
        output_splits: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_shrink_f32(
        input: *const f32,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_input_rows: *const u32,
        hidden: *mut f32,
        num_routes: i32,
        max_blocks: i32,
        block_size: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        max_rank: i32,
        input_mode: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_shrink_f16(
        input: *const f16,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_input_rows: *const u32,
        hidden: *mut f32,
        num_routes: i32,
        max_blocks: i32,
        block_size: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        max_rank: i32,
        input_mode: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_shrink_bf16(
        input: *const bf16,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_input_rows: *const u32,
        hidden: *mut f32,
        num_routes: i32,
        max_blocks: i32,
        block_size: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        max_rank: i32,
        input_mode: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_expand_f32(
        hidden: *const f32,
        output: *mut f32,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_routes: i32,
        max_blocks: i32,
        block_size: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        max_rank: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_expand_f16(
        hidden: *const f32,
        output: *mut f16,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_routes: i32,
        max_blocks: i32,
        block_size: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        max_rank: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_expand_bf16(
        hidden: *const f32,
        output: *mut bf16,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_routes: i32,
        max_blocks: i32,
        block_size: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        max_rank: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_wmma_f16(
        input: *const f16,
        output: *mut f16,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_input_rows: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_routes: i32,
        max_blocks: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        input_mode: i32,
        output_splits: i32,
        stream: CUstream,
    ) -> i32;

    pub fn launch_routed_lora_grouped_wmma_bf16(
        input: *const bf16,
        output: *mut bf16,
        weights: *const RoutedLoraAdapterWeight,
        sorted_route_ids: *const u32,
        block_pair_ids: *const u32,
        route_input_rows: *const u32,
        route_output_rows: *const u32,
        route_output_scales: *const f32,
        num_routes: i32,
        max_blocks: i32,
        top_k: i32,
        num_experts: i32,
        num_adapter_slots: i32,
        num_slices: i32,
        input_features: i32,
        output_features: i32,
        output_row_stride: i32,
        output_slice_stride: i32,
        input_mode: i32,
        output_splits: i32,
        stream: CUstream,
    ) -> i32;
}
