pub mod chat_completion;
mod completions;
pub mod defaults;
mod handlers;
mod image_generation;
pub mod mistralrs_for_server_builder;
pub mod mistralrs_server_router_builder;
pub mod openai;
pub mod openapi_doc;
mod speech_generation;
pub mod types;
mod util;
